<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ProposeRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
//            'proposeDetails'=>['required','array'],
//            'proposeDetails.*.company_name'=>['required','string','min:2','max:77'],
//            'proposeDetails.*.indicator'=>['required','string','min:2','max:77'],
//            'proposeDetails.*.value'=>['required','integer'],
//            'demand_id'=>['required','integer',Rule::exists('demands','id')],
//            'company_id'=>['required','integer'],
//            'offer_file'=>['required','mimes:pdf','max:2048'],
//            'description'=>['nullable','string'],


        ];
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub

    }
}
