    ("Abxaziya" , "Abxaziya Respublikası (Gürcüstan ərazisi)"),"
	("Akrotiri və Dekeliya" , "Akrotiri və Dekeliyanın Suveren Baza Rayonları (Böyük Britaniyanın xarici ərazisi)"),"
	("Aland adaları" , "Aland adaları	Aland adaları (Finlandiyanın muxtar əyaləti)	ALA"),
	("Albaniya Albaniya" , "Albaniya Respublikası	ALB"),
	("Almaniya Almaniya" , "Almaniya Federativ Respublikası	DEU"),
	("Amerika Samoası" , "Amerika Samoası	Amerikan Samoası Ərazisi (ABŞ ərazisi)	ASM"),
	("Andorra Andorra" , "Andorra Knyazlığı	AND"),
	("Angilya Angilya" , "Angilya (Böyük Britaniyanın xarici ərazisi)	AIA"),
	("Anqola" , "Anqola Respublikası	AGO"),
	("Antiqua və Barbuda" , "Antiqua və Barbuda	Antiqua və Barbuda	ATG"),
	("Argentina" , "Argentina Respublikası	ARG"),
	("Aruba" , "Aruba (Niderland Krallığında öz-özünü idarə edən ölkə)	ABW"),
	("Avstraliya" , "Avstraliya Birliyi	AUS"),
	("Avstriya" , "Avstriya Respublikası	AUT"),
	("Baham adaları" , "Baham adaları Birliyi	BHS"),
	("Banqladeş" , "Banqladeş Xalq Respublikası	BGD"),
	("Barbados" , "Barbados	BRB"),
	("Belçika" , "Belçika Krallığı	BEL"),
	("Beliz" , "Beliz	BLZ"),
	("Belarus" , "Belorusiya Respublikası	BLR"),
	("Benin" , "Benin Xalq Respublikası	BEN"),
	("Bermud adaları" , "Bermud adaları (Böyük Britaniyanın xarici ərazisi)	BMU"),
	("Birləşmiş Ərəb Əmirlikləri" , "BƏƏ	Birləşmiş Ərəb Əmirlikləri	ARE"),
	("ABŞ" , "Amerika Birləşmiş Ştatları	USA"),
	("Boliviya" , "Boliviya Respublikası	BOL"),
	("Bolqarıstan" , "Bolqarıstan Respublikası	BGR"),
	("Bosniya və Herseqovina" , "Bosniya və Herseqovina	Bosniya və Herseqovina	BIH"),
	("Botsvana" , "Botsvana Respublikası	BWA"),
	("Böyük Britaniya" , "Böyük Britaniya və Şimali İrlandiya Birləşmiş Krallığı	GBR"),
	("Braziliya" , "Braziliya Federativ Respublikası	BRA"),
	("Bruney" , "Bruney-Darussalam Sultanlığı	BRN"),
	("Burkina-Faso" , "Burkina-Faso	BFA"),
	("Burundi" , "Burundi Respublikası	BDI"),
	("Butan" , "Butan Krallığı	BTN"),
	("Bəhreyn" , "Bəhreyn Krallığı	BHR"),
	("Cersi" , "Cersi	 Beylifi (Britaniya Tac asılılığı)	JEY"),
	("Cəbəllütariq Cəbəli-Tariq" , "Cəbəli-Tariq (Böyük Britaniyanın xarici ərazisi)	GIB"),
	("Cənubi Afrika Respublikası" , "CAR	Cənubi Afrika Respublikası	ZAF"),
	("Cənubi Sudan" , "Cənubi Sudan	RSS"),
	("Cənubi Koreya" , "Koreya Respublikası	KOR"),
	("Cənubi Osetiya" , "Cənubi Osetiya Respublikası"),
	("Cibuti" , "Cibuti Respublikası	DJI"),
	("Çad" , "Çad Respublikası	TCD"),
	("Çexiya" , "Çex Respublikası	CZE"),
	("Monteneqro" , "Monteneqro	Qaradağ Respublikası (Çernoqoriya)	MNE"),
	("Çili" , "Çili Respublikası	CHL"),
	("Çin" , "Çin Xalq Respublikası	CHN"),
	("Danimarka" , "Danimarka Krallığı	DNK"),
	("Dominika" , "Dominika Birliyi	DMA"),
	("Dominikan Respublikası" , "Dominikan Respublikası	Dominikan Respublikası	DOM"),
	("Efiopiya" , "Efiopiya Federativ Demokratik Respublikası	ETH"),
    ("Ekvador" , "Ekvador Respublikası	ECU"),
	("Ekvatorial Qvineya" , "Ekvatorial Qvineya Respublikası	GNQ"),
	("Eritreya" , "Eritreya Dövləti	ERI"),
	("Ermənistan" , "Ermənistan Respublikası	ARM"),
	("Estoniya" , "Estoniya Respublikası	EST"),
	("Əfqanıstan" , "Əfqanıstan İslam Respublikası	AFG"),
	("Əlcəzair" , "Əlcəzair Xalq Demokratik Respublikası	DZA"),
	("Farer adaları" , "Farer adaları (Danimarka Krallığında öz-özünü idarə edən ölkə)	FRO"),
	("Fələstin Dövləti" , "Fələstin Əraziləri	PSE"),
	("Fici" , "Fici Adaları Respublikası	FJI"),
	("Kot-d'İvuar" , "Kot-d'İvuar	Fil Dişi Sahili Respublikası	CIV"),
	("Filippin" , "Filippin Respublikası	PHL"),
	("Finlandiya" , "Finlandiya Respublikası	FIN"),
	("Folklend adaları" , "Folklend adaları (Böyük Britaniyanın xarici ərazisi)	FLK"),
	("Fransa" , "Fransa Respublikası	FRA"),
	("Fransa Polineziyası" , "Fransa Polineziyası (Fransanın xarici birliyi)	PYF"),
	("Gernsi" , "Gernsi Beylifi (Britaniya Tac asılılığı)	GGY"),
	("Haiti" , "Haiti Respublikası	HTI"),
	("Hindistan" , "Hindistan Respublikası	IND"),
	("Honduras" , "Honduras Respublikası	HND"),
	("Honkonq" , "Çin Xalq Respublikasının Honkonq Xüsusi İnzibati Regionu (Xüsusi müstəqil oblastı)	HKG"),
	("Xorvatiya" , "Xorvatiya Respublikası	HRV"),
	("İndoneziya" , "İndoneziya Respublikası	IDN"),
	("İordaniya" , "İordaniya Həşimi Krallığı	JOR"),
	("İraq" , "İraq Respublikası	IRQ"),
	("İrlandiya" , "İrlandiya Respublikası	IRL"),
	("İslandiya" , "İslandiya Respublikası	ISL"),
	("İspaniya" , "İspaniya Krallığı	ESP"),
	("İsrail" , "İsrail Dövləti	ISR"),
	("İsveç" , "İsveç Krallığı	SWE"),
	("İsveçrə" , "İsveçrə Konfederasiyası	CHE"),
	("İtaliya" , "İtaliya Respublikası	ITA"),
	("Kabo-Verde" , "Kabo-Verde Respublikası	CPV"),
	("Kamboca" , "Kamboca Krallığı	KHM"),
	("Kamerun" , "Kamerun Respublikası	CMR"),
	("Kanada" , "Kanada	CAN"),
	("Kayman" , "Kayman adaları	Kayman adaları (Böyük Britaniyanın xarici ərazisi)	CYM"),
	("Keniya" , "Keniya Respublikası	KEN"),
	("Kipr" , "Kipr Respublikası	CYP"),
	("Kiribati" , "Kiribati Respublikası	KIR"),
    ("Kokos adaları" , "Kokos (Kilinq) adaları Ərazisi (Avstraliyanın xarici ərazisi)	CCK"),
	("Kolumbiya" , "Kolumbiya Respublikası	COL"),
	("Komor adaları" , "Komor adaları İttifaqı	COM"),
	("Konqo Respublikası" , "Konqo Respublikası	COG"),
	("Konqo Demokratik Respublikası KDR" , "Konqo Demokratik Respublikası	COD"),
	("Kosovo Kosovo" , "Kosovo Respublikası (Serbiya ərazisi)"),"
	("Kosta-Rika" , "Kosta-Rika Respublikası	CRI"),
	("Kuba" , "Kuba Respublikası	CUB"),
	("Kuk adaları" , "Kuk adaları (Yeni Zelandiyanın Əlaqəli ştatı)	COK"),
	("Küveyt Küveyt" , "Küveyt Dövləti	KWT"),
	("Qabon" , "Qabon Respublikası	GAB"),
	("Qambiya" , "Qambiya Respublikası	GMB"),
	("Qana" , "Qana Respublikası	GHA"),
	("Qətər" , "Qatar Dövləti	QAT"),
	("Qayana" , "Qayana Kooperativ Respublikası	GUY"),
	("Qazaxıstan" , "Qazaxıstan Respublikası	KAZ"),
	("Qərbi Saxara" , "Səhravi Ərəb Demokratik Respublikası	ESH"),
	("Qırğızıstan" , "Qırğızıstan Respublikası	KGZ"),
	("Qrenada" , "Qrenada	GRD"),
	("Qrenlandiya" , "Qrenlandiya (Danimarka Krallığında öz-özünü idarə edən ölkə)	GRL"),
	("Quam" , "Quam (ABŞ ərazisi)	GUM"),
	("Qvatemala" , "Qvatemala Respublikası	GTM"),
	("Qvineya" , "Qvineya Respublikası	GIN"),
	("Qvineya-Bisau" , "Qvineya-Bisau Respublikası	GNB"),
	("Laos" , "Laos Xalq Demokratik Respublikası	LAO"),
	("Latviya" , "Latviya Respublikası	LVA"),
	("Lesoto" , "Lesoto Krallığı	LSO"),
	("Liberiya" , "Liberiya Respublikası	LBR"),
	("Litva" , "Litva Respublikası	LTU"),
	("Livan" , "Livan Respublikası	LBN"),
	("Liviya" , "Böyük Liviya Ərəb Sosialist Xalq Cəmahiriyyəsi	LBY"),
	("Lixtenşteyn" , "Lixtenşteyn Knyazlığı	LIE"),
	("Lüksemburq" , "Lüksemburq Böyük Hersoqluğu	LUX"),
	("Macarıstan" , "Macarıstan Respublikası	HUN"),
	("Madaqaskar" , "Madaqaskar Respublikası	MDG"),
	("Makao Makao" , "Çin Xalq Respublikasının Makao Xüsusi İnzibati Regionu (Xüsusi müstəqil oblastı)	MAC"),
	("Şimali Makedoniya" , "Makedoniya Respublikası,BMTdə Keçmiş Yuqoslaviya Respublikası Makedoniya	MKD"),
	("Malavi" , "Malavi Respublikası	MWI"),
	("Malayziya" , "Malayziya Federasiyası	MYS"),
	("Maldiv adaları" , "Maldiv adaları Respublikası	MDV"),
	("Mali" , "Mali Respublikası	MLI"),
	("Malta" , "Malta Respublikası	MLT"),
	("Marşall adaları" , "Marşall adaları Respublikası	MHL"),
	("Mavriki" , "Mavrikiy Respublikası	MUS"),
	("Mavritaniya" , "Mavritaniya İslam Respublikası	MRT"),
	("Mayotta" , "Mayotta Departament Birliyi (Fransanın xarici birliyi)	MYT"),
	("Meksika" , "Meksika Birləşmiş Ştatları	MEX"),
	("Men adası" , "Men adası (Britaniya Tac asılılığı)	IMN"),
	("Mərakeş" , "Mərakeş Krallığı	MAR"),
	("Mərkəzi Afrika Respublikası" , "MAR	Mərkəzi Afrika Respublikası	CAF"),
	("Mikroneziya" , "Mikroneziya Federativ Ştatları	FSM"),
	("Milad adası" , "Milad adası (Avstraliyanın xarici ərazi'si')	CXR"),
	("Misir" , "Misir Ərəb Respublikası	EGY"),
	("Myanma" , "Myanma İttifaqı	MMR"),
	("Moldova" , "Moldova Respublikası	MDA"),
	("Monako" , "Monako Knyazlığı	MCO"),
	("Monqolustan" , "Monqolustan	Monqol Uls	MNG"),
	("Montserrat" , "Montserrat (Böyük Britaniyanın xarici ərazisi)	MSR"),
	("Mozambik" , "Mozambik Respublikası	MOZ"),
	("Namibiya" , "Namibiya Respublikası	NAM"),
	("Nauru" , "Nauru Respublikası	NRU"),
	("Nepal" , "Nepal Federativ Demokratik Respublikası	NPL"),
	("Niderland" , "Niderland Krallığı	NLD"),
	("Niderland Antil adaları" , "Niderland Antil adaları (Niderland Krallığında öz-özünü idarə edən ölkə)	ANT"),
	("Niger" , "Niger Respublikası	NER"),
	("Nigeriya" , "Nigeriya Federativ Respublikası	NGA"),
	("Nikaraqua" , "Nikaraqua Respublikası	NIC"),
	("Niue" , "Niue (Yeni Zelandiyanın Əlaqəli ştatı)	NIU"),
	("Norfolk adası" , "Norflok adası Ərazisi (Avstraliyanın xarici ərazisi)	NFK"),
	("Norveç" , "Norveç Krallığı	NOR"),
	("Oman" , "Oman Sultanlığı	OMN"),
	("Özbəkistan" , "Özbəkistan Respublikası	UZB"),
	("Pakistan" , "Pakistan İslam Respublikası	PAK"),
	("Palau" , "Palau Respublikası	PLW"),
	("Panama" , "Panama Respublikası	PAN"),
	("Papua-Yeni Qvineya" , "Papua-Yeni Qvineya Müstəqil Dövləti	PNG"),
	("Paraqvay" , "Paraqvay Respublikası	PRY"),
	("Peru" , "Peru Respublikası	PER"),
	("Pitkern adaları" , "Pitkern, Henderson, Ducie və Oeno adaları (Böyük Britaniyanın xarici ərazisi)	PCN"),
	("Polşa" , "Polşa Respublikası	POL"),
	("Portuqaliya" , "Portuqaliya Respublikası	PRT"),
	("Dnestryanı" , "Prednestroviya Moldovan Respublikası"),
	("Puerto-Riko" , "Puerto-Riko Birliyi (ABŞ birliyi)	PRI"),
	("Ruanda" , "Ruanda Respublikası	RWA"),
	("Rumıniya" , "Rumıniya	ROU"),
	("Salvador" , "El-Salvador Respublikası	SLV"),
	("Samoa" , "Samoa Müstəqil Dövləti	WSM"),
	("San-Marino" , "Şöhrətli San-Marino Respublikası	SMR"),
	("San-Tome və Prinsipi" , "San-Toma və Prinsipin Demokratik Respublikası	STP"),
	("Seneqal" , "Seneqal Respublikası	SEN"),
	("Sen-Bartelemi" , "Sent Bartelemi (Fransanın xarici birliyi)	BLM"),
	("Sent-Kits və Nevis" , "Sent Kits və Nevis (Sent Xristofer və Nevis Federasiyası)	KNA"),
	("Sent-Lüsiya" , "Sent Lusiya	LCA"),
	("Sen-Marten" , "Sent Martin Birliyi (Fransanın xarici birliyi)	MAF"),
	("Sen-Pyer və Mikelon" , "Sent Pyer və Mikelon Ərazi Birliyi (Fransanın xarici birliyi)	SPM"),
	("Sent-Vinsent və Qrenadin" , "Sent Vinsent və Qrenadinlər	VCT"),
	("Serbiya" , "Serbiya Respublikası	SRB"),
	("Seyşel adaları" , "Seyşel adaları Respublikası	SYC"),
	("Səudiyyə Ərəbistanı" , "Səudiyyə Ərəbistanı Krallığı	SAU"),
	("Sinqapur" , "Sinqapur Respublikası	SGP"),
	("Slovakiya" , "Slovakiya Respublikası	SVK"),
	("Sloveniya" , "Sloveniya Respublikası	SVN"),
	("Solomon adaları" , "Solomon adaları	SLB"),
	("Somali" , "Somali	SOM"),
	("Somalilend" , "Somalilənd Respublikası	SML"),
	("Sudan" , "Sudan Respublikası	SDN"),
	("Surinam" , "Surinam Respublikası	SUR"),
	("Suriya" , "Suriya Ərəb Respublikası	SYR"),
	("Esvatini" , "Esvatini Krallığı	ESW"),
	("Syerra-Leone" , "Syerra-Leone Respublikası	SLE"),
	("Şərqi Timor" , "Timor-Leste Demokratik Respublikası	TLS"),
	("Şimali Kipr Türk Respublikası" , "ŞKTR	Şimali Kipr Türk Respublikası (Kipr ərazisi)"),"
	("Şimali Koreya" , "KXDR	Koreya Xalq Demokratik Respublikası	PRK"),
	("Şimali Marian adaları" , "Şimali Marian adaları Birliyi (ABŞ birliyi)	MNP"),
	("Şpisbergen" , "Şpisbergen (Norveçin ərazisi)	SJM"),
	("Şri-Lanka" , "Şri-Lanka Demokratik Sosialist Respublikası	LKA"),
	("Tacikistan" , "Tacikistan Respublikası	TJK"),
	("Tanzaniya" , "Birləşmiş Tanzaniya Respublikası	TZA"),
	("Tailand" , "Tailand Krallığı	THA"),
	("Çin Respublikası" , "Çin Respublikası	TWN"),
	("Törks və Kaykos adaları" , "Terks və Kaykos adaları (Böyük Britaniyanın xarici ərazisi)	TCA"),
	("Tokelau" , "Tokelau (Yeni Zelandiyanın xarici ərazisi)	TKL"),
	("Tonqa" , "Tonqa Krallığı	TON"),
	("Toqo" , "Toqolez Respublikası	TGO"),
	("Trinidad və Tobaqo" , "Trinidad və Tobaqo Respublikası	TTO"),
	("Tunis" , "Tunis Respublikası	TUN"),
	("Tuvalu" , "Tuvalu	TUV"),
	("Türkmənistan" , "Türkmənistan	TKM"),
	("Ukrayna" , "Ukrayna	UKR"),
	("Uqanda" , "Uqanda Respublikası	UGA"),
	("Uruqvay" , "Uruqvay Şərq Respublikası	URY"),
	("Vanuatu" , "Vanuatu	VUT"),
	("Vatikan" , "Vatikan Şəhər Dövləti	VAT"),
	("Venesuela" , "Venesuela Bolivarian Respublikası	VEN"),
	("ABŞ Vircin adaları" , "ABŞ Virgin adaları	VIR"),
	("Britaniya Vircin adaları" , "Britaniya Virgin adaları	VGB"),
	("Vyetnam" , "Vyetnam Sosialist Respublikası	VNM"),
	("Yamayka" , "Yamayka	JAM"),
	("Yaponiya" , "Yaponiya	JPN"),
	("Yeni Kaledoniya" , "Yeni Kaledoniya Ərazisi və Asılılıqları (Fransa xüsusi birliyi)	NCL"),
	("Yeni Zelandiya" , "Yeni Zelandiya	NZL"),
	("Yəmən" , "Yəmən Respublikası	YEM"),
	("Yunanıstan" , "Yunanıstan Respublikası	GRC"),
	("Zambiya" , "Zambiya Respublikası	ZMB"),
	("Zimbabve" , "Zimbabve Respublikası")
